config/routes.rb
Jcb::Application.routes.draw do

  resources :words
  resources :sentences
  root :to => "sessions#home"
  match "/ji" => "words#ji"

  match "/home" => "sessions#home"
  match "/admin" => "sessions#admin"
  match "/gen" => "sessions#gen"
  match "/mail" => "sessions#mail"
  get "sessions/create"
  get "sessions/failure"
  match '/auth/:provider/callback', :to => 'sessions#create'
  match '/auth/failure', :to => 'sessions#failure'
  match 'logout' => 'sessions#destroy'

end

app/models/sentence.rb
class Sentence < ActiveRecord::Base
  belongs_to :user
  has_many :words
  attr_protected :user_id
end

app/controllers/sentences_controller.rb
#!/bin/env ruby
# encoding: utf-8
class SentencesController < ApplicationController
  before_filter :has_user, :except => [:index, :create]
  protected
  def has_user
    unless @current_user
      flash[:warning] = '请先登录从而使用记词本功能。'
      redirect_to sentence_path(params[:sentence_id])
    end
  end
  public

  def index
    @sentences = Sentence.where("user_id = ?", @current_user).order("updated_at DESC").limit(20)
  end

  def show
    unless self.check_user(Sentence, params[:id]) == 'stop'
      @sentence_id = params[:id]
      @sentence = Sentence.find @sentence_id
      @words = Word.where("sentence_id = ?", @sentence).order("updated_at DESC")
    end
  end

  def create
    @sentence = Sentence.new(params[:sentence])
    @sentence.user = @current_user
    if @sentence.save
      flash[:notice] = "成功将句子“#{@sentence.title}”加入记词本!"
      if params[:commit] == "添加句子"
        redirect_to sentences_path
      elsif params[:commit] == "添加并连接单词"
        redirect_to sentence_path(@sentence)
      end
    else
      flash[:error] = 'Error:: '
      for error in @sentence.errors.full_messages
        flash[:error] += error
      end
      redirect_to sentences_path       
    end
  end

  def edit
    unless self.check_user(Sentence, params[:id]) == 'stop'
      @sentence = Sentence.find params[:id]
      @sentence.updated_at = Time.now
    end
  end

  def update
    unless self.check_user(Sentence, params[:id]) == 'stop'
      @sentence = Sentence.find params[:id]
      if @sentence.update_attributes params[:sentence]
        flash[:notice] = "“#{@sentence.title}”成功更新！"
        redirect_to sentences_path
      else
        flash[:error] = 'Error:: '
        for error in @sentence.errors.full_messages
          flash[:error] += error
        end
        redirect_to edit_sentence_path(@sentence)
      end
    end
  end

  def destroy
    unless self.check_user(Sentence, params[:id]) == 'stop'
      @sentence = Sentence.find(params[:id])
      @words = Word.where("sentence_id = ?", @sentence)
      for word in @words
        word.sentence_id = nil
        word.save
      end
      @sentence.destroy
      flash[:notice] = "成功删除句子“#{@sentence.title}”并去除相关单词链接！"
      redirect_to sentences_path
    end
  end

end

app/views/sentences/_sentence_editing_form.html.haml
= label :sentence, :title, '句子'
= text_area :sentence, :title, :class => ["input-block-level"]
= label :sentence, :in_chinese, '中文翻译'
= text_area :sentence, :in_chinese, :class => ["in_chinese", "input-block-level"]

app/views/sentences/_sentences_list_with_related_words.html.haml
%table#sentences
  %thead
    %tr
      %th 句子及相关单词
      %th 
  %tbody
    - @sentences.each do |sentence|
      %tr#original_tr
        %td#tr_sentence_title= link_to sentence.title, edit_sentence_path(sentence)
        %td= link_to "相关单词", sentence_path(sentence)  
      %tr#translated_tr
        %td.in_chinese#tr_sentence_in_chinese= sentence.in_chinese
        %td= sentence.created_at.to_date
      %tr#related_words_tr
        %td#tr_related_words
          - for word in sentence.words
            = link_to word.title, edit_word_path(word)
            = ':'
            %span.in_chinese= word.in_chinese
            = '；'
        %td= ""

app/views/sentences/_sentences_list_without_related_words.html.haml
%table#sentences
  %thead
    %tr
      %th 句子及翻译
      %th 
  %tbody
    - @sentences.each do |sentence|
      %tr#original_tr
        %td#tr_sentence_title= link_to sentence.title, edit_sentence_path(sentence)
        %td= link_to "相关单词", sentence_path(sentence)  
      %tr#translated_tr
        %td.in_chinese#tr_sentence_in_chinese= sentence.in_chinese
        %td= sentence.created_at.to_date

app/views/sentences/edit.html.haml
%h2 句子编辑
%h3#sentence= link_to @sentence.title, sentence_path(@sentence)
= form_tag sentence_path(@sentence), :method => :put, :id => "sentences_form" do
  = render :partial => 'sentence_editing_form'
  = label :sentence, :add_date, '修改最近更新时间'
  = datetime_select :sentence, :updated_at, :use_month_numbers => true
  %div
    = submit_tag '更新句子'
= button_to '删除句子', sentence_path(@sentence), :method => :delete, :confirm => 'Are you sure?'
= button_to '取消编辑', sentences_path, :method => :get

app/views/sentences/index.html.haml
-#  This file is app/views/sentences/index.html.haml
%h2 添加新句子
= form_tag sentences_path, :method => :post, :id => "sentences_form" do
  = render :partial => 'sentence_editing_form'
  %div= submit_tag '添加句子'
  %div= submit_tag '添加并连接单词'

%h2=link_to"最近编辑过的句子", sentences_path
= render :partial => 'sentences_list_with_related_words'

app/views/sentences/show.html.haml
%h2 为此句子添加相关单词
%h3#sentence= link_to @sentence.title, edit_sentence_path(@sentence)
%h3.in_chinese= @sentence.in_chinese
= form_tag words_path(:sentence_id => @sentence_id), :method => :post do
  = label :word, :title, '单词'
  = text_field :word, :title 
  = label :word, :in_chinese, '中文释义'
  = text_field :word, :in_chinese 
  %div= submit_tag '添加'

%h2 已关联单词
=render :partial => '/words/words_list'